### ISSUE TITLE
Instability when installing wazuh-server on debian-12 EC2 launched by allocator: Another process is using APT

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-installation-assistant#189]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  v4.10.0-rc2  |  41007  |  Development  | Installation-assistant   | Assistant | 

## Description

The [Deployability](https://github.com/wazuh/wazuh/issues/27358) tests are failing in the manager tests with the following error. In these tests the wizard is used to install wazuh-server on various operating systems.
Analysis were done here: https://github.com/wazuh/wazuh-qa-automation/issues/584

The `debian-12` has an unstable installation and the following error message is displayed:

```
Another process is using APT. Waiting for it to release the lock
```

In

```
'02/01/2025 11:45:08 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.002/01/2025 11:45:08 INFO: Verbose logging redirected to /var/log/wazuh-install.log02/01/2025 11:45:08 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.02/01/2025 11:45:08 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.02/01/2025 11:45:12 INFO: --- Dependencies ----02/01/2025 11:45:12 INFO: Installing gawk.02/01/2025 11:45:17 WARNING: Hardware checks ignored.02/01/2025 11:45:17 INFO: --- Dependencies ----02/01/2025 11:45:17 INFO: Installing lsof.02/01/2025 11:45:20 INFO: --- Dependencies ----02/01/2025 11:45:20 INFO: Installing apt-transport-https.02/01/2025 11:45:20 INFO: Installing software-properties-common.02/01/2025 11:45:31 INFO: Installing gnupg.02/01/2025 11:45:34 INFO: Wazuh development repository added.02/01/2025 11:45:35 INFO: --- Wazuh server ---02/01/2025 11:45:35 INFO: Starting the Wazuh manager installation.02/01/2025 11:46:38 INFO: Wazuh manager installation finished.02/01/2025 11:46:38 INFO: Wazuh manager vulnerability detection configuration finished.02/01/2025 11:46:38 INFO: Starting service wazuh-manager.02/01/2025 11:46:56 INFO: wazuh-manager service started.02/01/2025 11:46:56 INFO: Starting Filebeat installation.02/01/2025 11:46:56 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (1/10)02/01/2025 11:47:27 ERROR: Filebeat installation failed.02/01/2025 11:47:27 INFO: --- Removing existing Wazuh installation ---02/01/2025 11:47:27 INFO: Removing Wazuh manager.02/01/2025 11:47:27 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (1/10)02/01/2025 11:47:57 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (2/10)02/01/2025 11:48:27 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (3/10)02/01/2025 11:48:57 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (4/10)02/01/2025 11:49:27 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 30 seconds (5/10)02/01/2025 11:50:06 INFO: Wazuh manager removed.02/01/2025 11:50:06 INFO: --- Dependencies ----02/01/2025 11:50:06 INFO: Removing gawk.02/01/2025 11:50:07 INFO: Removing lsof.02/01/2025 11:50:08 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.'
```

There is apparently a conflict between the APT helper on `debian-12` and it is required to investigate if it is due to a problem with the image used by the allocator or due to a problem with the helper.
on `debian-11` and `debian-10` no problems have been seen. All tests have been done on AWS

### Environment

AWS `debian-12` EC2 launched by Allocation module, size: `large` (c5ad.xlarge + 30gbs)

### Steps to reproduce

Run the following steps allows running DTT tests on an Ubuntu 22.04 EC2 with more than 8 vCPUs

<details>

## Configurate AWS credentials and profile

```
mkdir ~/.aws/
nano ~/.aws/credentials 
```

Add
```
[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```

```
nano ~/.aws/config
```
Add
```
[default]
region = us-east-1
output = json
```

## Get repository

```
git clone https://user:xxx@github.com/wazuh/wazuh-qa-automation.git
cd /home/ubuntu/wazuh-qa-automation
git checkout 4.10.0
git checkout bug/584-deployability-wazuh-manager-test-fail
```
(the branch bug/584-deployability-wazuh-manager-test-fail has some changes in order to see the manager installation logs)

## Create environment and provision it
```
sudo apt update
sudo apt install python3-venv
python3 -m venv env
source env/bin/activate
```

Install awscli
```
pip3 install awscli
```

Install ansible
```
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
```

Install Jobflow
```
cd /home/ubuntu/wazuh-qa-automation
pip3 uninstall -y jobflow && pip3 install tools/jobflow
```

## Adjust templates and run

Manager
```
cd /home/ubuntu/wazuh-qa-automation/tests/test_functional/test_system/test_deployability
rm templates/manager/Test-manager-complete.yaml 
nano templates/manager/Test-manager-complete.yaml 
```

Copy the following yaml file (set wazuh-qa-automation issue number and gh token)

<details><summary>YAML file</summary>

```
version: 0.1
description: This workflow is used to test manager deployment for DDT
variables:
  tests-dir: "/home/ubuntu/wazuh-qa-automation/tests/test_functional/test_system/test_deployability/tests"
  manager-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-ubuntu-24.04-amd64
    - linux-amazon-2-amd64
    - linux-redhat-7-amd64
    - linux-redhat-8-amd64
    - linux-redhat-9-amd64
    - linux-centos-7-amd64
    - linux-centos-8-amd64
    - linux-debian-10-amd64
    - linux-debian-11-amd64
    - linux-debian-12-amd64

  infra-provider: aws
  working-dir: /tmp/dtt1-poc
  version: "4.10.0"
  revision: "41007"

  # Allocator variables
  allocator-branch: "v4.10.0-rc2"
  allocator-repository: "https://xxx@github.com/wazuh/wazuh-automation.git"
  allocator-workingdir: "/tmp/dtt1-poc/wazuh-automation"
  allocator-script: "/tmp/dtt1-poc/wazuh-automation/deployability/modules/allocation/main.py"

  # Wazuh QA automation variables
  qa-branch: "v4.10.0-rc2"
  qa-repository: "https://xxx@github.com/wazuh/wazuh-qa-automation.git"
  qa-workingdir: "/tmp/wazuh-qa-automation"
  testing_dir: "/tmp/wazuh-qa-automation/tools/testing"

tasks:
  # Clone allocator
  - task: "clone-allocator-repo"
    description: "Clone allocator repository"
    do:
      this: process
      with:
        path: git
        args:
          - clone
          - branch: "{allocator-branch}"
          - "{allocator-repository}"
          - "{allocator-workingdir}"
    cleanup:
      this: process
      with:
        path: rm
        args:
          - "-rf"
          - "{allocator-workingdir}"

  # Install allocator dependencies
  - task: "allocator-ready"
    description: "Make allocator ready"
    do:
      this: process
      with:
        path: pip3
        args:
          - install
          - requirement: "{allocator-workingdir}/deployability/deps/requirements.txt"
    depends-on:
      - "clone-allocator-repo"

  # Clone wazuh-qa-automation
  - task: "clone-wazuh-qa-automation-repo"
    description: "Clone wazuh-qa-automation repository"
    do:
      this: process
      with:
        path: git
        args:
          - clone
          - branch: "{qa-branch}"
          - "{qa-repository}"
          - "{qa-workingdir}"
    cleanup:
      this: process
      with:
        path: rm
        args:
          - "-rf"
          - "{qa-workingdir}"

  # Install Testing tool
  - task: "install-testing-tool"
    description: "Install Testing tool"
    do:
      this: process
      with:
        path: pip3
        args:
          - install
          - "{testing_dir}"
    depends-on:
      - "clone-wazuh-qa-automation-repo"

  # Unique manager allocate task
  - task: "allocate-manager-{manager}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - "{allocator-script}"
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager}"
          - inventory-output: "{working-dir}/manager-{manager}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa-automation/issues/xxx"
    on-error: "abort-all"
    foreach:
      - variable: manager-os
        as: manager
    cleanup:
      this: process
      with:
        path: python3
        args:
          - "{allocator-script}"
          - action: delete
          - track-output: "{working-dir}/manager-{manager}/track.yaml"
    depends-on:
      - "allocator-ready"

  # Generic manager test task
  - task: "run-manager-tests"
    description: "Run tests install for the manager."
    do:
      this: process
      with:
        path: testing
        args:
          - tests-dir: "{tests-dir}"
          - targets:
            - wazuh-1: "{working-dir}/manager-linux-centos-7-amd64/inventory.yaml"
            - wazuh-2: "{working-dir}/manager-linux-ubuntu-20.04-amd64/inventory.yaml"
            - wazuh-3: "{working-dir}/manager-linux-ubuntu-22.04-amd64/inventory.yaml"
            - wazuh-4: "{working-dir}/manager-linux-ubuntu-24.04-amd64/inventory.yaml"
            - wazuh-5: "{working-dir}/manager-linux-redhat-7-amd64/inventory.yaml"
            - wazuh-6: "{working-dir}/manager-linux-redhat-8-amd64/inventory.yaml"
            - wazuh-7: "{working-dir}/manager-linux-redhat-9-amd64/inventory.yaml"
            - wazuh-8: "{working-dir}/manager-linux-centos-8-amd64/inventory.yaml"
            - wazuh-9: "{working-dir}/manager-linux-debian-10-amd64/inventory.yaml"
            - wazuh-10: "{working-dir}/manager-linux-debian-11-amd64/inventory.yaml"
            - wazuh-11: "{working-dir}/manager-linux-debian-12-amd64/inventory.yaml"
            - wazuh-12: "{working-dir}/manager-linux-amazon-2-amd64/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "manager"
          - wazuh-version: "{version}"
          - wazuh-revision: "{revision}"
          - live: False
    depends-on:
      - "install-testing-tool"
      - "allocate-manager-linux-ubuntu-20.04-amd64"
      - "allocate-manager-linux-ubuntu-22.04-amd64"
      - "allocate-manager-linux-ubuntu-24.04-amd64"
      - "allocate-manager-linux-amazon-2-amd64"
      - "allocate-manager-linux-redhat-7-amd64"
      - "allocate-manager-linux-redhat-8-amd64"
      - "allocate-manager-linux-redhat-9-amd64"
      - "allocate-manager-linux-centos-7-amd64"
      - "allocate-manager-linux-centos-8-amd64"
      - "allocate-manager-linux-debian-10-amd64"
      - "allocate-manager-linux-debian-11-amd64"
      - "allocate-manager-linux-debian-12-amd64"

```
</details>

Run

```
python3 -m jobflow templates/manager/Test-manager-complete.yaml --threads 7 --log-level=DEBUG | tee manager.txt
```
Check the manager.txt

</details>

### Current result

Instability when installing wazuh-server on `debian-12`. Appearance of the error mentioned above

Previously notified:
- https://github.com/wazuh/wazuh-qa/issues/5832
- https://github.com/wazuh/wazuh-qa-automation/issues/589

### Expected result

Stable installation

### Attachments

- Logs: https://github.com/user-attachments/files/18290614/manager_log.txt
